version: "3.7"
services:

  laravel:
    build:
      context: api
      dockerfile: Dockerfile
    container_name: laravel
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./api:/var/www/
      - ./api/supervisor/conf.d:/etc/supervisor/conf.d
    command: bash -c "if [ ! -f .env ]; then cp .env.example .env; fi && ([ -d vendor ] || composer install --no-interaction --prefer-dist --optimize-autoloader) && php-fpm"
    networks:
      - network_default

  nginx:
    image: nginx:1.20-alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./api:/var/www
      - ./infra/nginx:/etc/nginx/templates
    networks:
      - network_default

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - network_default

  spa:
    build: './spa'
    container_name: spa
    ports:
      - '80:3000'
    networks:
      - network_default

networks:
  network_default:
    driver: bridge
