name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, bcmath
          coverage: none

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress --no-suggest
        working-directory: ./api

      - name: Copy .env
        run: cp .env.example .env
        working-directory: ./api

      - name: Generate application key
        run: php artisan key:generate
        working-directory: ./api

      - name: Run tests
        run: php artisan test
        working-directory: ./api